export const licenseAttachmentWorkflowsAbi = [
    {
        inputs: [
            { internalType: 'address', name: 'accessController', type: 'address' },
            { internalType: 'address', name: 'coreMetadataModule', type: 'address' },
            { internalType: 'address', name: 'ipAssetRegistry', type: 'address' },
            { internalType: 'address', name: 'licenseRegistry', type: 'address' },
            { internalType: 'address', name: 'licensingModule', type: 'address' },
            { internalType: 'address', name: 'pilTemplate', type: 'address' },
        ],
        stateMutability: 'nonpayable',
        type: 'constructor',
    },
    { inputs: [{ internalType: 'address', name: 'authority', type: 'address' }], name: 'AccessManagedInvalidAuthority', type: 'error' },
    {
        inputs: [
            { internalType: 'address', name: 'caller', type: 'address' },
            { internalType: 'uint32', name: 'delay', type: 'uint32' },
        ],
        name: 'AccessManagedRequiredDelay',
        type: 'error',
    },
    { inputs: [{ internalType: 'address', name: 'caller', type: 'address' }], name: 'AccessManagedUnauthorized', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'target', type: 'address' }], name: 'AddressEmptyCode', type: 'error' },
    { inputs: [{ internalType: 'address', name: 'implementation', type: 'address' }], name: 'ERC1967InvalidImplementation', type: 'error' },
    { inputs: [], name: 'ERC1967NonPayable', type: 'error' },
    { inputs: [], name: 'FailedCall', type: 'error' },
    { inputs: [], name: 'InvalidInitialization', type: 'error' },
    {
        inputs: [
            { internalType: 'address', name: 'caller', type: 'address' },
            { internalType: 'address', name: 'signer', type: 'address' },
        ],
        name: 'LicenseAttachmentWorkflows__CallerNotSigner',
        type: 'error',
    },
    { inputs: [], name: 'LicenseAttachmentWorkflows__NoLicenseTermsData', type: 'error' },
    { inputs: [], name: 'LicenseAttachmentWorkflows__ZeroAddressParam', type: 'error' },
    { inputs: [], name: 'NotInitializing', type: 'error' },
    { inputs: [], name: 'PermissionHelper__ModulesAndSelectorsMismatch', type: 'error' },
    { inputs: [], name: 'UUPSUnauthorizedCallContext', type: 'error' },
    { inputs: [{ internalType: 'bytes32', name: 'slot', type: 'bytes32' }], name: 'UUPSUnsupportedProxiableUUID', type: 'error' },
    { inputs: [], name: 'Workflow__CallerNotAuthorizedToMint', type: 'error' },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'address', name: 'authority', type: 'address' }],
        name: 'AuthorityUpdated',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: false, internalType: 'uint64', name: 'version', type: 'uint64' }],
        name: 'Initialized',
        type: 'event',
    },
    {
        anonymous: false,
        inputs: [{ indexed: true, internalType: 'address', name: 'implementation', type: 'address' }],
        name: 'Upgraded',
        type: 'event',
    },
    {
        inputs: [],
        name: 'ACCESS_CONTROLLER',
        outputs: [{ internalType: 'contract IAccessController', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'CORE_METADATA_MODULE',
        outputs: [{ internalType: 'contract ICoreMetadataModule', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'IP_ASSET_REGISTRY',
        outputs: [{ internalType: 'contract IIPAssetRegistry', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'LICENSE_REGISTRY',
        outputs: [{ internalType: 'contract ILicenseRegistry', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'LICENSING_MODULE',
        outputs: [{ internalType: 'contract ILicensingModule', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'PIL_TEMPLATE',
        outputs: [{ internalType: 'contract IPILicenseTemplate', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'UPGRADE_INTERFACE_VERSION',
        outputs: [{ internalType: 'string', name: '', type: 'string' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [],
        name: 'authority',
        outputs: [{ internalType: 'address', name: '', type: 'address' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'accessManager', type: 'address' }],
        name: 'initialize',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'isConsumingScheduledOp',
        outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'spgNftContract', type: 'address' },
            { internalType: 'address', name: 'recipient', type: 'address' },
            {
                components: [
                    { internalType: 'string', name: 'ipMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'ipMetadataHash', type: 'bytes32' },
                    { internalType: 'string', name: 'nftMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'nftMetadataHash', type: 'bytes32' },
                ],
                internalType: 'struct WorkflowStructs.IPMetadata',
                name: 'ipMetadata',
                type: 'tuple',
            },
            { internalType: 'bool', name: 'allowDuplicates', type: 'bool' },
        ],
        name: 'mintAndRegisterIpAndAttachDefaultTerms',
        outputs: [
            { internalType: 'address', name: 'ipId', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'spgNftContract', type: 'address' },
            { internalType: 'address', name: 'recipient', type: 'address' },
            {
                components: [
                    { internalType: 'string', name: 'ipMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'ipMetadataHash', type: 'bytes32' },
                    { internalType: 'string', name: 'nftMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'nftMetadataHash', type: 'bytes32' },
                ],
                internalType: 'struct WorkflowStructs.IPMetadata',
                name: 'ipMetadata',
                type: 'tuple',
            },
            {
                components: [
                    {
                        components: [
                            { internalType: 'bool', name: 'transferable', type: 'bool' },
                            { internalType: 'address', name: 'royaltyPolicy', type: 'address' },
                            { internalType: 'uint256', name: 'defaultMintingFee', type: 'uint256' },
                            { internalType: 'uint256', name: 'expiration', type: 'uint256' },
                            { internalType: 'bool', name: 'commercialUse', type: 'bool' },
                            { internalType: 'bool', name: 'commercialAttribution', type: 'bool' },
                            { internalType: 'address', name: 'commercializerChecker', type: 'address' },
                            { internalType: 'bytes', name: 'commercializerCheckerData', type: 'bytes' },
                            { internalType: 'uint32', name: 'commercialRevShare', type: 'uint32' },
                            { internalType: 'uint256', name: 'commercialRevCeiling', type: 'uint256' },
                            { internalType: 'bool', name: 'derivativesAllowed', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesAttribution', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesApproval', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesReciprocal', type: 'bool' },
                            { internalType: 'uint256', name: 'derivativeRevCeiling', type: 'uint256' },
                            { internalType: 'address', name: 'currency', type: 'address' },
                            { internalType: 'string', name: 'uri', type: 'string' },
                        ],
                        internalType: 'struct PILTerms',
                        name: 'terms',
                        type: 'tuple',
                    },
                    {
                        components: [
                            { internalType: 'bool', name: 'isSet', type: 'bool' },
                            { internalType: 'uint256', name: 'mintingFee', type: 'uint256' },
                            { internalType: 'address', name: 'licensingHook', type: 'address' },
                            { internalType: 'bytes', name: 'hookData', type: 'bytes' },
                            { internalType: 'uint32', name: 'commercialRevShare', type: 'uint32' },
                            { internalType: 'bool', name: 'disabled', type: 'bool' },
                            { internalType: 'uint32', name: 'expectMinimumGroupRewardShare', type: 'uint32' },
                            { internalType: 'address', name: 'expectGroupRewardPool', type: 'address' },
                        ],
                        internalType: 'struct Licensing.LicensingConfig',
                        name: 'licensingConfig',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct WorkflowStructs.LicenseTermsData[]',
                name: 'licenseTermsData',
                type: 'tuple[]',
            },
            { internalType: 'bool', name: 'allowDuplicates', type: 'bool' },
        ],
        name: 'mintAndRegisterIpAndAttachPILTerms',
        outputs: [
            { internalType: 'address', name: 'ipId', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
            { internalType: 'uint256[]', name: 'licenseTermsIds', type: 'uint256[]' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'bytes[]', name: 'data', type: 'bytes[]' }],
        name: 'multicall',
        outputs: [{ internalType: 'bytes[]', name: 'results', type: 'bytes[]' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: '', type: 'address' },
            { internalType: 'address', name: '', type: 'address' },
            { internalType: 'uint256', name: '', type: 'uint256' },
            { internalType: 'bytes', name: '', type: 'bytes' },
        ],
        name: 'onERC721Received',
        outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [],
        name: 'proxiableUUID',
        outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'nftContract', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
            {
                components: [
                    { internalType: 'string', name: 'ipMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'ipMetadataHash', type: 'bytes32' },
                    { internalType: 'string', name: 'nftMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'nftMetadataHash', type: 'bytes32' },
                ],
                internalType: 'struct WorkflowStructs.IPMetadata',
                name: 'ipMetadata',
                type: 'tuple',
            },
            {
                components: [
                    { internalType: 'address', name: 'signer', type: 'address' },
                    { internalType: 'uint256', name: 'deadline', type: 'uint256' },
                    { internalType: 'bytes', name: 'signature', type: 'bytes' },
                ],
                internalType: 'struct WorkflowStructs.SignatureData',
                name: 'sigMetadataAndDefaultTerms',
                type: 'tuple',
            },
        ],
        name: 'registerIpAndAttachDefaultTerms',
        outputs: [{ internalType: 'address', name: 'ipId', type: 'address' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'nftContract', type: 'address' },
            { internalType: 'uint256', name: 'tokenId', type: 'uint256' },
            {
                components: [
                    { internalType: 'string', name: 'ipMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'ipMetadataHash', type: 'bytes32' },
                    { internalType: 'string', name: 'nftMetadataURI', type: 'string' },
                    { internalType: 'bytes32', name: 'nftMetadataHash', type: 'bytes32' },
                ],
                internalType: 'struct WorkflowStructs.IPMetadata',
                name: 'ipMetadata',
                type: 'tuple',
            },
            {
                components: [
                    {
                        components: [
                            { internalType: 'bool', name: 'transferable', type: 'bool' },
                            { internalType: 'address', name: 'royaltyPolicy', type: 'address' },
                            { internalType: 'uint256', name: 'defaultMintingFee', type: 'uint256' },
                            { internalType: 'uint256', name: 'expiration', type: 'uint256' },
                            { internalType: 'bool', name: 'commercialUse', type: 'bool' },
                            { internalType: 'bool', name: 'commercialAttribution', type: 'bool' },
                            { internalType: 'address', name: 'commercializerChecker', type: 'address' },
                            { internalType: 'bytes', name: 'commercializerCheckerData', type: 'bytes' },
                            { internalType: 'uint32', name: 'commercialRevShare', type: 'uint32' },
                            { internalType: 'uint256', name: 'commercialRevCeiling', type: 'uint256' },
                            { internalType: 'bool', name: 'derivativesAllowed', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesAttribution', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesApproval', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesReciprocal', type: 'bool' },
                            { internalType: 'uint256', name: 'derivativeRevCeiling', type: 'uint256' },
                            { internalType: 'address', name: 'currency', type: 'address' },
                            { internalType: 'string', name: 'uri', type: 'string' },
                        ],
                        internalType: 'struct PILTerms',
                        name: 'terms',
                        type: 'tuple',
                    },
                    {
                        components: [
                            { internalType: 'bool', name: 'isSet', type: 'bool' },
                            { internalType: 'uint256', name: 'mintingFee', type: 'uint256' },
                            { internalType: 'address', name: 'licensingHook', type: 'address' },
                            { internalType: 'bytes', name: 'hookData', type: 'bytes' },
                            { internalType: 'uint32', name: 'commercialRevShare', type: 'uint32' },
                            { internalType: 'bool', name: 'disabled', type: 'bool' },
                            { internalType: 'uint32', name: 'expectMinimumGroupRewardShare', type: 'uint32' },
                            { internalType: 'address', name: 'expectGroupRewardPool', type: 'address' },
                        ],
                        internalType: 'struct Licensing.LicensingConfig',
                        name: 'licensingConfig',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct WorkflowStructs.LicenseTermsData[]',
                name: 'licenseTermsData',
                type: 'tuple[]',
            },
            {
                components: [
                    { internalType: 'address', name: 'signer', type: 'address' },
                    { internalType: 'uint256', name: 'deadline', type: 'uint256' },
                    { internalType: 'bytes', name: 'signature', type: 'bytes' },
                ],
                internalType: 'struct WorkflowStructs.SignatureData',
                name: 'sigMetadataAndAttachAndConfig',
                type: 'tuple',
            },
        ],
        name: 'registerIpAndAttachPILTerms',
        outputs: [
            { internalType: 'address', name: 'ipId', type: 'address' },
            { internalType: 'uint256[]', name: 'licenseTermsIds', type: 'uint256[]' },
        ],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'ipId', type: 'address' },
            {
                components: [
                    {
                        components: [
                            { internalType: 'bool', name: 'transferable', type: 'bool' },
                            { internalType: 'address', name: 'royaltyPolicy', type: 'address' },
                            { internalType: 'uint256', name: 'defaultMintingFee', type: 'uint256' },
                            { internalType: 'uint256', name: 'expiration', type: 'uint256' },
                            { internalType: 'bool', name: 'commercialUse', type: 'bool' },
                            { internalType: 'bool', name: 'commercialAttribution', type: 'bool' },
                            { internalType: 'address', name: 'commercializerChecker', type: 'address' },
                            { internalType: 'bytes', name: 'commercializerCheckerData', type: 'bytes' },
                            { internalType: 'uint32', name: 'commercialRevShare', type: 'uint32' },
                            { internalType: 'uint256', name: 'commercialRevCeiling', type: 'uint256' },
                            { internalType: 'bool', name: 'derivativesAllowed', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesAttribution', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesApproval', type: 'bool' },
                            { internalType: 'bool', name: 'derivativesReciprocal', type: 'bool' },
                            { internalType: 'uint256', name: 'derivativeRevCeiling', type: 'uint256' },
                            { internalType: 'address', name: 'currency', type: 'address' },
                            { internalType: 'string', name: 'uri', type: 'string' },
                        ],
                        internalType: 'struct PILTerms',
                        name: 'terms',
                        type: 'tuple',
                    },
                    {
                        components: [
                            { internalType: 'bool', name: 'isSet', type: 'bool' },
                            { internalType: 'uint256', name: 'mintingFee', type: 'uint256' },
                            { internalType: 'address', name: 'licensingHook', type: 'address' },
                            { internalType: 'bytes', name: 'hookData', type: 'bytes' },
                            { internalType: 'uint32', name: 'commercialRevShare', type: 'uint32' },
                            { internalType: 'bool', name: 'disabled', type: 'bool' },
                            { internalType: 'uint32', name: 'expectMinimumGroupRewardShare', type: 'uint32' },
                            { internalType: 'address', name: 'expectGroupRewardPool', type: 'address' },
                        ],
                        internalType: 'struct Licensing.LicensingConfig',
                        name: 'licensingConfig',
                        type: 'tuple',
                    },
                ],
                internalType: 'struct WorkflowStructs.LicenseTermsData[]',
                name: 'licenseTermsData',
                type: 'tuple[]',
            },
            {
                components: [
                    { internalType: 'address', name: 'signer', type: 'address' },
                    { internalType: 'uint256', name: 'deadline', type: 'uint256' },
                    { internalType: 'bytes', name: 'signature', type: 'bytes' },
                ],
                internalType: 'struct WorkflowStructs.SignatureData',
                name: 'sigAttachAndConfig',
                type: 'tuple',
            },
        ],
        name: 'registerPILTermsAndAttach',
        outputs: [{ internalType: 'uint256[]', name: 'licenseTermsIds', type: 'uint256[]' }],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [{ internalType: 'address', name: 'newAuthority', type: 'address' }],
        name: 'setAuthority',
        outputs: [],
        stateMutability: 'nonpayable',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'newImplementation', type: 'address' },
            { internalType: 'bytes', name: 'data', type: 'bytes' },
        ],
        name: 'upgradeToAndCall',
        outputs: [],
        stateMutability: 'payable',
        type: 'function',
    },
]
